version: '0'

services:

  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: VerySeriousPasswordHere123
      MYSQL_DATABASE: Effort
    ports:
      - "3308:3306"